---

- name: spin up the load balancer and add the servers to it
  hosts: 127.0.0.1
  connection: local
  gather_facts: False
  tasks:
    - name: setup a simple load balancer
      ec2_elb_lb:
        name: aws-elb-demo
        state: present
        region: us-east-1
        zones:
          - us-east-1a
        listeners:
          - protocol: http
            load_balancer_port: 80
            instance_port: 80
      register: aws-elb-demo

    - name: add the webservers to the load balancer
      local_action: ec2_elb
      args:
        instance_id: i-0b181ea6460a68598
        ec2_elbs: aws-elb-demo
        state: present
        region: us-east-2
      with_items: ec2.tagged_instances

    - name: add the webservers to the load balancer
      local_action: ec2_elb
      args:
        instance_id: i-0b9f93cfa809e945c
        ec2_elbs: aws-elb-demo
        state: present
        region: us-east-2
      with_items: ec2.tagged_instances
